# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate random deviates from a von Mises distribution
#'
#' This function generates random deviates from a von Mises distribution with
#' parameters, mu and k (ie kappa).
#'
#' A random deviate for a circular normal distribution has the form:\cr
#' \deqn{f(theta; mu, kappa) = 1 / (2*pi*I0(kappa)) * exp(kappa*cos(theta-mu))}
#' theta is within 0 and 2*pi.
#'
#' \code{I0(kappa)} in the normalizing constant is the modified Bessel
#' function of the first kind and order zero.
#'
#' @param n number of observations.
#' @param mu mean direction of the distribution.
#' @param k kappa parameter. A positive numeric value for the concentration
#' parameter of the distribution.
#'
#' @return a column vector
#' @examples
#' n  <- 100
#' mu <- 0
#' k  <- 10
#' vm_de <- rvm(n, mu, k)      ## in degree unit
#' vm_pi <- vm_de %% (2 * pi)  ## in radian unit
#' @export
rvm <- function(n, mu, k) {
    .Call('CircularDDM_rvm', PACKAGE = 'CircularDDM', n, mu, k)
}

#' Find First k Positive Zeros for the Bessel Functions
#'
#' This function finds the first k positive zeros of the Bessel function
#' J(n, x) or Y(n, x) using Halley's method.
#'
#' @param nu The order of the corresponding Bessel function.
#' @param k an integer for the first k positive zeros.
#' @param kind 0, 1, or 2. A switch selects \link{besselI}, \link{besselJ} or
#' \link{besselY}
#'
#' @return a column vector
#' @references
#' \href{http://au.mathworks.com/matlabcentral/fileexchange/6794-bessel-function-zeros/content/besselzero.m}{besselzero.m}
#' @examples
#' nu <- seq(0, 5, length.out=10)
#' output <- matrix(numeric(5*length(nu)), nrow=5)
#' for (i in 1:length(nu)) { output[,i] <- besselzero(nu[i], 5, 1) }
#' print(output)
#'
#' output <- matrix(numeric(5*length(nu)), nrow=5)
#' for(i in 1:length(nu)) { output[,i] <- besselzero(nu[i], 5, 2) }
#' print(output)
#' @export
besselzero <- function(nu, k, kind) {
    .Call('CircularDDM_besselzero', PACKAGE = 'CircularDDM', nu, k, kind)
}

#' Log-Likelihood for Continuous Reports
#'
#' Calculate log-likelihood of the continuous reports, using
#' equation (23) on p 433 in Smith (2016).
#'
#' This function does not do 'exp' in Smith (2016, p433), so it calculates
#' log-likelihood, instead of just likelihood.
#'
#' @param x a matrix storing a first column of RT and a second column of
#' continuous responses/reports. Each row is a trial.
#' @param pVec a parameter vector with the order [a, vx, vy, t0, sv_sq], which
#' are decision threshold, drift rate along x axis,  drift rate along y axis,
#' non-decision time, and within trial variance.
#'
#' @return a column vector
#' @references Smith, P. L. (2016). Diffusion Theory of Decision Making in
#' Continuous Report, Psychological Review, 123 (4), 425--451.
#' @examples
#' ## An example data, showing the format of input data to logLik_resp
#' x <- cbind (
#' RT=c(1.2595272, 0.8693937, 0.8009044, 1.0018933, 2.3640007, 1.0521304),
#' R =c(1.9217430, 1.7844653, 0.2662521, 2.1569724, 1.7277440, 0.8607271)
#' )
#' pVec <- c(a=2.45, vx=1.5, vy=1.25, t0=.1, s=1)
#' den  <- logLik_resp(x, pVec=pVec); den
#' @export
logLik_resp <- function(x, pVec) {
    .Call('CircularDDM_logLik_resp', PACKAGE = 'CircularDDM', x, pVec)
}

#' Log-Likelihood for Circular First Passage Time
#'
#' Calculate circular log-likelihood of the first passage time, using
#' equation (22) on page 432. Note this function return log density so as to
#' be compatiable with \code{logLik_resp}. Equation (22) in Smith (2016)
#' describes the density function.
#'
#' @param x a matrix storing a first column of RT and a second column of
#' continuous responses/reports. Each row is a trial.
#' @param pVec a parameter vector with the order [a, vx, vy, t0, s].
#' a stands for response threshold, vx is the drift rate along x axis,
#' vy is the drift rate along y axis, t0 is the non-decision time, and s
#' is the within-trial variance.
#' @param k a precision for bessel function. The larger the k is, the larger
#' the memory space is required. Default is 141.
#'
#' @return a column vector
#' @references Smith, P. L. (2016). Diffusion Theory of Decision Making in
#' Continuous Report, Psychological Review, 123 (4), 425--451.
#' @examples
#' x <- cbind(
#' RT=c(1.2595272, 0.8693937, 0.8009044, 1.0018933, 2.3640007, 1.0521304),
#' R =c(1.9217430, 1.7844653, 0.2662521, 2.1569724, 1.7277440, 0.8607271)
#' )
#' pVec <- c(a=2.45, vx=1.5, vy=1.25, t0=.1, s=1)
#' den  <- logLik_dt(x, pVec=pVec);
#' den
#' @export
logLik_dt <- function(x, pVec, k = 141L) {
    .Call('CircularDDM_logLik_dt', PACKAGE = 'CircularDDM', x, pVec, k)
}

#' The Circular Drift-diffusion Distribution
#'
#' Density function for the circular drift-diffusion model with theta
#' vector equal to \code{pVec}.  \code{dcddm} is the
#' equation (23) on page 433 in Smith (2016).
#'
#' @param x a matrix storing a first column of RT and a second column of
#' continuous responses/reports. Each row is a trial.
#' @param pVec a parameter vector with the order [a, vx, vy, t0, s].
#' a stands for response threshold, vx is the drift rate along x axis,
#' vy is the drift rate along y axis, t0 is the non-decision time, and s
#' is the within-trial variance. The order matters.
#' @param k a precision for calculating the infinite series in \code{dcddm}.
#' The larger the k is, the larger the memory space is required. Default is
#' 141.
#' @return \code{dcddm} gives a likelihood column vector.
#' @references Smith, P. L. (2016). Diffusion Theory of Decision Making in
#' Continuous Report, Psychological Review, 123 (4), 425--451.
#' @examples
#' ## dcddm example
#' x <- cbind(
#' RT= c(1.2595272, 0.8693937, 0.8009044, 1.0018933, 2.3640007, 1.0521304),
#' R = c(1.9217430, 1.7844653, 0.2662521, 2.1569724, 1.7277440, 0.8607271)
#' )
#' pVec <- c(a=2.45, vx=1.5, vy=1.25, t0=.1, s=1)
#' dcddm(x, pVec)
#' @export
dcddm <- function(x, pVec, k = 141L) {
    .Call('CircularDDM_dcddm', PACKAGE = 'CircularDDM', x, pVec, k)
}

#' The Circular Drift-diffusion Distribution
#'
#' Generate random deviates for the circular drift-diffusion
#' model with a theta vector, namely \code{pVec}. \code{rcddm1} is a canonical
#' form of the random number generator for circular drift-diffusion model.
#' \code{rcddm2} is an extension, allowing one to supply a threshold vector,
#' an angle vector, a starting point matrix [xPos, yPos] and a non-decision
#' time.
#'
#' @param n number of observations.
#' @param pVec a parameter vector with the order [a, vx, vy, t0, sv_sq].
#' a stands for response threshold, vx is the drift rate along x axis,
#' vy is the drift rate along y axis, t0 is the non-decision time, and sv_sq
#' is the within-trial variance. The order matters.
#' @param p a precision for random walk step in \code{rcddm}. Default is 0.15
#' second
#' @param angle an angle vector, allowing one to supply a vector of random
#' draws from an arbitary, instead of von Mise, distribution.
#' @param threshold a threshold vector.
#' @param sp a starting point matrix.  First column must be the x coordinate
#' of the starting point and the second column must be the y coordinate of
#' the starting point. Each row is a random deviate.
#' @param t0 non-decision time. Must be a scalar.
#' @param tol an upper bound (step) for the drift-diffusion process. This
#' prevents an unrealistic threshold been enterd from falling into while loop
#' trap. Default is 1,000 steps.
#'
#' @return a n x 2 matrix with two columns: RTs and angles.
#' @references Smith, P. L. (2016). Diffusion Theory of Decision Making in
#' Continuous Report, Psychological Review, 123 (4), 425--451.
#' @examples
#' ## rcddm1 example
#' pVec <- c(a=2, vx=1.5, vy=1.25, t0=.25, s=1)
#' den  <- rcddm1(1e3, pVec);
#' hist(den[,1], breaks = "fd", xlab="Response Time",  main="Density")
#' hist(den[,2], breaks = "fd", xlab="Response Angle", main="Density")
#'
#' ## rcddm2 example
#' t0 <- .25
#' threshold <- runif(10, 0, 2)
#' angle <- rvm(1e3, 0, 10)
#' startpoint <- cbind(runif(10, 0, 1), runif(10, 0,1))
#' den  <- rcddm2_internal(1e3, threshold, angle, startpoint, t0)
#' head(den)
#'
#' ## If starting points only has one row, this is equilvalent to fixing
#' ## the starting points at constant values. This is because internally the
#' ## function will always use the first row when 'sp' is a row vector.
#' ## Similarly, one can apply the same trick on threshold and angle vectors.
#' startpoint <- cbind(runif(1, 0, 1),  runif(1, 0,1));
#' den  <- rcddm2(1e3, threshold, angle, startpoint, t0)
#'
#' ## If the user enters a R's vector, which is not a matrix,
#' ## rcddm2 wrapper helps the user to convert it to a matrix (ie row vector)
#' ## Note this flexibility requires checking steps.
#' den  <- rcddm2(1e3, threshold, angle, startpoint, t0)
#'
#' @export
rcddm1 <- function(n, pVec, p = 0.15) {
    .Call('CircularDDM_rcddm1', PACKAGE = 'CircularDDM', n, pVec, p)
}

#' @rdname rcddm1
#' @export
rcddm2_internal <- function(n, threshold, angle, sp, t0, p = 0.15, tol = 1e3L) {
    .Call('CircularDDM_rcddm2_internal', PACKAGE = 'CircularDDM', n, threshold, angle, sp, t0, p, tol)
}

